List<String> alphabets = [
  'https://github.com/srishtiv27/give_me_a_sign/blob/main/assets/images/alphabets/A.png?raw=true',
  'https://github.com/srishtiv27/give_me_a_sign/blob/main/assets/images/alphabets/B.png?raw=true',
  'https://github.com/srishtiv27/give_me_a_sign/blob/main/assets/images/alphabets/C.png?raw=true',
  'https://github.com/srishtiv27/give_me_a_sign/blob/main/assets/images/alphabets/D.png?raw=true',
  'https://github.com/srishtiv27/give_me_a_sign/blob/main/assets/images/alphabets/E.png?raw=true',
  'https://github.com/srishtiv27/give_me_a_sign/blob/main/assets/images/alphabets/F.png?raw=true',
  'https://github.com/srishtiv27/give_me_a_sign/blob/main/assets/images/alphabets/G.png?raw=true',
  'https://github.com/srishtiv27/give_me_a_sign/blob/main/assets/images/alphabets/H.png?raw=true',
  'https://github.com/srishtiv27/give_me_a_sign/blob/main/assets/images/alphabets/I.png?raw=true',
  'https://github.com/srishtiv27/give_me_a_sign/blob/main/assets/images/alphabets/J.png?raw=true',
  'https://github.com/srishtiv27/give_me_a_sign/blob/main/assets/images/alphabets/K.png?raw=true',
  'https://github.com/srishtiv27/give_me_a_sign/blob/main/assets/images/alphabets/L.png?raw=true',
  'https://github.com/srishtiv27/give_me_a_sign/blob/main/assets/images/alphabets/M.png?raw=true',
  'https://github.com/srishtiv27/give_me_a_sign/blob/main/assets/images/alphabets/N.png?raw=true',
  'https://github.com/srishtiv27/give_me_a_sign/blob/main/assets/images/alphabets/O.png?raw=true',
  'https://github.com/srishtiv27/give_me_a_sign/blob/main/assets/images/alphabets/P.png?raw=true',
  'https://github.com/srishtiv27/give_me_a_sign/blob/main/assets/images/alphabets/Q.png?raw=true',
  'https://github.com/srishtiv27/give_me_a_sign/blob/main/assets/images/alphabets/R.png?raw=true',
  'https://github.com/srishtiv27/give_me_a_sign/blob/main/assets/images/alphabets/S.png?raw=true',
  'https://github.com/srishtiv27/give_me_a_sign/blob/main/assets/images/alphabets/T.png?raw=true',
  'https://github.com/srishtiv27/give_me_a_sign/blob/main/assets/images/alphabets/U.png?raw=true',
  'https://github.com/srishtiv27/give_me_a_sign/blob/main/assets/images/alphabets/V.png?raw=true',
  'https://github.com/srishtiv27/give_me_a_sign/blob/main/assets/images/alphabets/W.png?raw=true',
  'https://github.com/srishtiv27/give_me_a_sign/blob/main/assets/images/alphabets/X.png?raw=true',
  'https://github.com/srishtiv27/give_me_a_sign/blob/main/assets/images/alphabets/Y.png?raw=true',
  'https://github.com/srishtiv27/give_me_a_sign/blob/main/assets/images/alphabets/Z.png?raw=true',
];

List<String> numbers = [
  "https://github.com/srishtiv27/give_me_a_sign/blob/main/assets/images/numbers/1.gif?raw=true",
  "https://github.com/srishtiv27/give_me_a_sign/blob/main/assets/images/numbers/2.gif?raw=true",
  "https://github.com/srishtiv27/give_me_a_sign/blob/main/assets/images/numbers/3.gif?raw=true",
  "https://github.com/srishtiv27/give_me_a_sign/blob/main/assets/images/numbers/4.gif?raw=true",
  "https://github.com/srishtiv27/give_me_a_sign/blob/main/assets/images/numbers/5.gif?raw=true",
  "https://github.com/srishtiv27/give_me_a_sign/blob/main/assets/images/numbers/6.gif?raw=true",
  "https://github.com/srishtiv27/give_me_a_sign/blob/main/assets/images/numbers/7.gif?raw=true",
  "https://github.com/srishtiv27/give_me_a_sign/blob/main/assets/images/numbers/8.gif?raw=true",
  "https://github.com/srishtiv27/give_me_a_sign/blob/main/assets/images/numbers/9.gif?raw=true",
  "https://github.com/srishtiv27/give_me_a_sign/blob/main/assets/images/numbers/10.gif?raw=true",
  "https://github.com/srishtiv27/give_me_a_sign/blob/main/assets/images/numbers/11.gif?raw=true",
  "https://github.com/srishtiv27/give_me_a_sign/blob/main/assets/images/numbers/12.gif?raw=true",
  "https://github.com/srishtiv27/give_me_a_sign/blob/main/assets/images/numbers/13.gif?raw=true",
  "https://github.com/srishtiv27/give_me_a_sign/blob/main/assets/images/numbers/14.gif?raw=true",
  "https://github.com/srishtiv27/give_me_a_sign/blob/main/assets/images/numbers/15.gif?raw=true",
  "https://github.com/srishtiv27/give_me_a_sign/blob/main/assets/images/numbers/16.gif?raw=true",
  "https://github.com/srishtiv27/give_me_a_sign/blob/main/assets/images/numbers/17.gif?raw=true",
  "https://github.com/srishtiv27/give_me_a_sign/blob/main/assets/images/numbers/18.gif?raw=true",
  "https://github.com/srishtiv27/give_me_a_sign/blob/main/assets/images/numbers/19.gif?raw=true",
  "https://github.com/srishtiv27/give_me_a_sign/blob/main/assets/images/numbers/20.gif?raw=true",
  "https://github.com/srishtiv27/give_me_a_sign/blob/main/assets/images/numbers/50.gif?raw=true",
  "https://github.com/srishtiv27/give_me_a_sign/blob/main/assets/images/numbers/100.gif?raw=true",
];

List<String> days = [
  "https://github.com/srishtiv27/give_me_a_sign/blob/main/assets/images/days/Monday.gif?raw=true",
  "https://github.com/srishtiv27/give_me_a_sign/blob/main/assets/images/days/tuesday.gif?raw=true",
  "https://github.com/srishtiv27/give_me_a_sign/blob/main/assets/images/days/Wednesday.gif?raw=true",
  "https://github.com/srishtiv27/give_me_a_sign/blob/main/assets/images/days/thursday.gif?raw=true",
  "https://github.com/srishtiv27/give_me_a_sign/blob/main/assets/images/days/Friday.gif?raw=true",
  "https://github.com/srishtiv27/give_me_a_sign/blob/main/assets/images/days/saturday.gif?raw=true",
  "https://github.com/srishtiv27/give_me_a_sign/blob/main/assets/images/days/Sunday.gif?raw=true",
];

List<String> months = [
  'https://github.com/srishtiv27/give_me_a_sign/blob/main/assets/images/months/January.gif?raw=true',
  'https://github.com/srishtiv27/give_me_a_sign/blob/main/assets/images/months/February.gif?raw=true',
  'https://github.com/srishtiv27/give_me_a_sign/blob/main/assets/images/months/March.gif?raw=true',
  'https://github.com/srishtiv27/give_me_a_sign/blob/main/assets/images/months/April.gif?raw=true',
  'https://github.com/srishtiv27/give_me_a_sign/blob/main/assets/images/months/May.gif?raw=true',
  'https://github.com/srishtiv27/give_me_a_sign/blob/main/assets/images/months/June.gif?raw=true',
  'https://github.com/srishtiv27/give_me_a_sign/blob/main/assets/images/months/July.gif?raw=true',
  'https://github.com/srishtiv27/give_me_a_sign/blob/main/assets/images/months/August.gif?raw=true',
  'https://github.com/srishtiv27/give_me_a_sign/blob/main/assets/images/months/September.gif?raw=true',
  'https://github.com/srishtiv27/give_me_a_sign/blob/main/assets/images/months/October.gif?raw=true',
  'https://github.com/srishtiv27/give_me_a_sign/blob/main/assets/images/months/November.gif?raw=true',
  'https://github.com/srishtiv27/give_me_a_sign/blob/main/assets/images/months/December.gif?raw=true',
];
